# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledprice',
            options={'verbose_name': 'Agendamento de Cobrança', 'verbose_name_plural': 'Agendamentos de Cobranças'},
        ),
        migrations.RemoveField(
            model_name='scheduledprice',
            name='service',
        ),
    ]
