# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing_control', '0002_auto_20170819_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledprice',
            name='count',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledprice',
            name='unit_price',
            field=models.FloatField(default=django.utils.timezone.now, verbose_name='Valor unitário'),
            preserve_default=False,
        ),
    ]
