# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_crud', '0003_auto_20170723_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='email',
            field=models.EmailField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
