# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_crud', '0005_auto_20170724_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='type',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='tipo'),
        ),
    ]
