# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_crud', '0007_auto_20170726_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='phones',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='phones',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telefones'),
        ),
        migrations.DeleteModel(
            name='CustomerPhone',
        ),
    ]
